# Nom pour le workflow
name: Mon Context

# On précise quel est le déclencheur de notre workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Infos de mon context github
        run: echo "${{ toJson(github) }}"

      - name: Mes variables d'environnement
        env:
          MA_VARIABLE: ${{ vars.MA_VARIABLE }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Le secret est ${{ MY_SECRET }}"
          echo "La variable est ${{ MA_VARIABLE }}"

