# Nom pour le workflow
name: Mon Context

# On précise quel est le déclencheur de notre workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Infos de mon context github
        run: echo "${{ toJson(github) }}"

